version: '3.7'

services:
  
  app-server:
    container_name: app
    depends_on:
      - db
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/docker?useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - common-network

  # Database Service (Mysql)
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - common-network
    
  jenkins:
    container_name: jenkins
    user: root
    privileged: true
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

networks:
  common-network:
    driver: bridge

volumes:
  db_data:
    driver: local