version: '3.7'

services:
  
  app-server:
    container_name: app
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 

  # Database Service (Mysql)
  db:
    container_name: db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    
  jenkins:
    container_name: jenkins
    user: root
    privileged: true
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker